- name: Reset Kubernetes installation
  shell: "kubeadm reset"
  when: "reset==true"

- name: Initialize Kubernetes cluster for ARM with flannel support
  shell: "kubeadm init --token {{ token }} --pod-network-cidr={{cidr}} --api-external-dns-names kubernetes {{ master }}"

- name: Install Networking Pods
  shell: "curl -sSL 'https://github.com/coreos/flannel/blob/master/Documentation/kube-flannel.yml?raw=true' | 'sed s/amd64/{{arch}}/g' | kubectl create -f -"
  register: out

- debug: var=out.stdout_lines  

- name: Download cluster configuration
  fetch: src=/etc/kubernetes/admin.conf dest=./kubeconfig/